apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/jstrachan/bdd-test-rust-http-1530536708:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/jstrachan/bdd-test-rust-http-1530536708:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: bdd-test-rust-http-1530536708
        chartPath: charts/bdd-test-rust-http-1530536708
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/jstrachan/bdd-test-rust-http-1530536708"
          image.tag: "{{.TAG}}"
